namespace Fireblocks.Client.Enums;

public enum TransferPeerPathResponseType
{
	VAULT_ACCOUNT = 1,
	EXCHANGE_ACCOUNT,
	INTERNAL_WALLET,
	EXTERNAL_WALLET,
	ONE_TIME_ADDRESS,
	NETWORK_CONNECTION,
	FIAT_ACCOUNT,
	COMPOUND,
	UNKNOWN
}
