namespace Fireblocks.Client.Enums;

public enum TransactionDestinationType
{
	VAULT_ACCOUNT = 1,
	EXCHANGE_ACCOUNT,
	INTERNAL_WALLET,
	EXTERNAL_WALLET,
	ONE_TIME_ADDRESS,
	FIAT_ACCOUNT,
	NETWORK_CONNECTION,
	COMPOUND
}
